### ISSUE TITLE
Add popup menu like maya shelf

### ISSUE THREAD

**Issue by SPluzh** [Vaei/FloatingShelf#1]
Description:
It would be great to enhance the floating shelf by adding a popup menu feature similar to Maya's shelf. This would allow users to access additional commands or functionality via a right-click context menu, making the floating shelf even more versatile and efficient.

Feature Request:

Implement a right-click popup menu for the floating shelf.
Allow users to add and customize commands or scripts within this popup menu.
Benefits:

Improved workflow efficiency with quick access to additional tools.
Enhanced customization, aligning the floating shelf closer to the Maya shelf functionality.
Looking forward to your feedback!

**Comment by Vaei** [comment]
There is already a right-click menu.

**Comment by SPluzh** [comment]
![Maya_Jz9dhknWDe](https://github.com/user-attachments/assets/71a4529c-03d3-4615-b96c-b0e80565aa3f)
I see, I meant adding a context menu where users can add their own custom commands. Currently, the right-click menu exists, but it would be great if it were customizable to allow users to add specific commands or scripts.
